=== Vmvs007/ESTG-LEI/Processamento Estruturado de Informação/8170278/DocumentosXML/storeXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.BikeOnTrack.pt/Store"
	targetNamespace="http://www.BikeOnTrack.pt/Store"
	xmlns:c="http://www.BikeOnTrack.pt/CommonTypes"
	xmlns:ex="http://www.BikeOnTrack.pt/Exercise"
	elementFormDefault="qualified">
	
	<xs:import schemaLocation="CommonTypesXSD.xsd" namespace="http://www.BikeOnTrack.pt/CommonTypes"/>
	<xs:import schemaLocation="exerciseXSD.xsd" namespace="http://www.BikeOnTrack.pt/Exercise"/>

	
	<xs:element name="store">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="storeID" type="xs:positiveInteger"/>
				<xs:element name="name" type="xs:string"/>			
				<xs:element name="nif" type="c:typeNIF" minOccurs="0" maxOccurs="1"/>
				<xs:element name="address" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="street" type="xs:string"/>
							<xs:element name="doorNum" type="xs:integer"/>
							<xs:element name="postalCode" type="c:typeZipCode"/>
							<xs:element name="city" type="xs:string"/>
							<xs:element name="district" type="xs:string"/>
							<xs:element name="country" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="contacts" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="phone" type="c:typePhone"/>
							<xs:element name="email" type="c:typeEmail"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="totalProducts" type="xs:integer"/>
				<xs:element name="totalSales" type="xs:double"/>
				<xs:element name="avegePrice" type="xs:double"/>
				<xs:element name="exercise" type="ex:exercise" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Vmvs007/ESTG-LEI/Processamento Estruturado de Informação/8170278/store.xml
<?xml version="1.0" encoding="UTF-8"?>

<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns="http://www.BikeOnTrack.pt/Store"
	xsi:schemaLocation="http://www.BikeOnTrack.pt/Store storeXSD.xsd">

	<name>Famabike - Comércio de Bicicletas, Lda</name>
	<storeID>00001</storeID>
	<nif>505123456</nif>
	<address>
		<street>Rua António Ferreira de Matos</street>
		<doorNum>9</doorNum>
		<postalCode>4760-018</postalCode>
		<city>Vila Nova de Famalicão</city>
		<district>Porto</district>
		<country>Portugal</country>
	</address>
	<contacts>
		<phone>913455077</phone>
		<email>famabike@famabike.com</email>
	</contacts>
</store>
